### PR TITLE
Update rc522.c to not output init message

### PR DESCRIPTION
**Pull request by Philluxx**
Do not output init message to avoid init message as scanned id output

### CODE REVIEW

**Review by funnierinspanish — APPROVED** [review]

**Comment by funnierinspanish** [comment]
@ocsacesar can you please merge?

**Comment by ocsacesar** [comment]
@UnJavaScripter Thank you for your pull request.

**Comment by htaoufikallah** [comment]
@ocsacesar pleaze update npm with this commit.

**Comment by ocsacesar** [comment]
I'm sorry for the late reply
The new version was published on NPM.
Enjoy it.

**Comment by htaoufikallah** [comment]
@ocsacesar thanks 👍

**Pull request merged**
